server.port: 8761
spring:
  application:
    name: discovery-service
  security:
    user:
      name: username
      password: password
logging:
  level:
    com.netflix.eureka: debug
    com.netflix.discovery: debug
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false