spring:
  application:
    name: discovery-service
logging:
  level:
    com.netflix.eureka: debug
    com.netflix.discovery: debug
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false