server.port: 8080
logging:
  level:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///home/vu/coding/vitamax-config
---
spring:
  config.activate.on-profile: dev
  cloud.config.server.git:
    uri: git@github.com:vfor4/vitamax-config.git
    ignore-local-ssh-settings: true
    host-key-algorithm: ssh-ed25519
    host-key: ${GIT_HOST_KEY}
    private-key: ${GIT_PRIVATE_KEY}