server.port: 8080
logging:
  level:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file://${VITAMAX_CONFIG_PATH}