server:
  port: 8443
  ssl:
    bundle: gateway-bundle
app.eureka-server: localhost
management:
  endpoint.health.show-details: "ALWAYS"
  endpoints.web.exposure.include: "*"
spring:
  application.name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${app.auth.host}:${app.auth.port}/oauth2/jwks
  cloud:
    config.enabled: false
    gateway.server.webflux:
      httpclient.connect-timeout: 5000
      routes:
        - id: auth-service
          uri: http://${app.auth.host}:${app.auth.port}
          predicates:
            - Path=/oauth2/**,/.well-known/**
        - id: course-composite
          uri: ${app.course-composite-service.uri}
          predicates:
            - Path=/api/**,/openapi/**
          filters:
            - name: CircuitBreaker
              args:
                name: course-composite-circuit-breaker
                fallbackUri: forward:/fallback
        - id: eureka-web-start
          uri: http://${app.eureka.host}:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: eureka-web-other
          uri: http://${app.eureka.host}:8761
          predicates:
            - Path=/eureka/**
  ssl:
    bundle:
      pem:
        gateway-bundle:
          keystore:
            certificate: classpath:/certificates/cert.pem
            private-key: classpath:/certificates/key.pem
resilience4j:
  circuitbreaker:
    instances:
      course-composite-circuit-breaker:
        sliding-window-size: 10
        minimum-number-of-calls: 10
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 60
  timelimiter:
    instances:
      course-composite-circuit-breaker:
        timeout-duration: 10s
eureka.client.service-url.defaultZone: http://username:password@${app.eureka.host}:8761/eureka/
app:
  eureka:
    host: localhost
  auth:
    host: localhost
    port: 9000
  course-composite-service:
    uri: http://localhost:7005