server.port: 8888
management:
  endpoint.health.show-details: "ALWAYS"
  endpoints.web.exposure.include: "*"
spring:
  application.name: gateway-service
  cloud:
    gateway.server.webflux:
      httpclient.connect-timeout: 5000
      routes:
        - id: course-composite
          uri: http://localhost:7005
          predicates:
            - Path=/api/**,/openapi/**
          filters:
            - name: CircuitBreaker
              args:
                name: course-composite-circuit-breaker
                fallbackUri: forward:/fallback
resilience4j:
  circuitbreaker:
    instances:
      course-composite-circuit-breaker:
        sliding-window-size: 10
        minimum-number-of-calls: 10
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 60
  timelimiter:
    instances:
      course-composite-circuit-breaker:
        timeout-duration: 10s