app.eureka-server: localhost
eureka.client.register-with-eureka: false
management:
  endpoint.health.show-details: "ALWAYS"
  endpoints.web.exposure.include: "*"
logging:
  level:
    root: debug
spring:
  application.name: gateway-service
  config.import: "optional:configserver:"
  main.web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          httpclient.connect-timeout: 5000
          routes:
            - id: course-composite
              uri: http://localhost:7005
              predicates:
                - Path=/api/**,/openapi/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: course-composite-circuit-breaker
                    fallbackUri: forward:/fallback
                    statusCodes:
                      - 500
                      - 404
            - id: eureka-web-start
              uri: http://localhost:8761
              predicates:
                - Path=/eureka/web
              filters:
                - SetPath=/
            - id: eureka-web-other
              uri: http://localhost:8761
              predicates:
                - Path=/eureka/**
---
spring.config.activate.on-profile: dev
spring.cloud.config:
  uri: http://config:8080
  fail-fast: true
  retry:
    max-attempts: 10
    initial-interval: 1100
    max-interval: 1500
    multiplier: 1.2
