server.port: 7003
spring:
  application:
    name: recommendation-service
  data:
    mongodb:
      host: "127.0.0.1"
      port: 27017
      auto-index-creation: true
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  cloud:
    function:
      definition: recommendationCreate;recommendationUpdate;recommendationDelete
    stream:
      default:
        group: ${spring.application.name}
        consumer:
          max-attempts: 3
          back-off-initial-interval: 1000
          back-off-max-interval: 10000
          back-off-multiplier: 2.0
      bindings:
        recommendationCreate-in-0:
          destination: recommendation.create
        recommendationUpdate-in-0:
          destination: recommendation.update
        recommendationDelete-in-0:
          destination: recommendation.delete
eureka:
  instance:
    appname: ${spring.application.name}
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
  client:
    initialInstanceInfoReplicationIntervalSeconds: 10
    registryFetchIntervalSeconds: 5

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb
      port: 27017
server.port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/