server.port: 7003
spring:
  application:
    name: recommendation-service
  data:
    mongodb:
      host: "127.0.0.1"
      port: 27017
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  cloud:
    stream:
      bindings:
        recommendation-in-0:
          destination: recommendation
          group: recommendation-service
eureka:
  instance:
    appname: ${spring.application.name}
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
  client:
    initialInstanceInfoReplicationIntervalSeconds: 10
    registryFetchIntervalSeconds: 5

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb
      port: 27017
server.port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/