server.port: 7003
spring:
  application.name: recommendation-service
  config.import: "optional:configserver:"
  data:
    mongodb:
      host: "127.0.0.1"
      port: 27017
      auto-index-creation: true
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  cloud:
    function:
      definition: recommendationCreate;recommendationUpdate;recommendationDelete
    stream:
      default:
        group: ${spring.application.name}
        consumer:
          max-attempts: 3
          back-off-initial-interval: 1000
          back-off-max-interval: 10000
          back-off-multiplier: 2.0
      bindings:
        recommendationCreate-in-0:
          destination: recommendation.create
        recommendationUpdate-in-0:
          destination: recommendation.update
        recommendationDelete-in-0:
          destination: recommendation.delete
eureka:
  client:
    fetch-registry: false

---
spring.config.activate.on-profile: dev
spring.cloud.config:
  uri: http://config:8080
  fail-fast: true
  retry:
    max-attempts: 10
    initial-interval: 1100
    max-interval: 1500
    multiplier: 1.2
