server:
  port: 9000
  forward-headers-strategy: framework
spring:
  application.name: auth-service
auth:
  private-key-location: classpath:certificates/private.pem
  public-key-location: classpath:certificates/public.pem