#!/usr/bin/env bash
#
# Sample usage:
#
#   HOST=localhost PORT=7001 ./test-em-all.bash
#
: ${HOST=localhost}
: ${PORT=8080}
: ${COURSE_ID_REVS_RECS=1}
: ${COURSE_ID_NOT_FOUND=99}
: ${COURSE_ID_NO_RECS=2}
: ${COURSE_ID_NO_REVS=3}


function assertHttpCode() {
  local expectedHttpCode=$1
  shift
  local temp=$(mktemp)
  local httpCode=$(curl -s -o "$temp" -w "%{http_code}" "$@")
  local body=$(cat "$temp")

  rm -f "$temp"

  if [ "$httpCode" = "$expectedHttpCode" ]
  then
    echo "$body"
  else
    echo  "Test FAILED, EXPECTED HTTP Code: $expectedHttpCode, GOT: $httpCode, WILL ABORT!"
    echo  "- Failing command: $@"
    echo  "- Response Body: $body"
    exit 1
  fi
}

function assertEqual() {
  local expected=$1
  local actual=$2

  if [ "$actual" = "$expected" ]
  then
    echo "Test OK (actual value: $actual)"
  else
    echo "Test FAILED, EXPECTED VALUE: $expected, ACTUAL VALUE: $actual, WILL ABORT"
    exit 1
  fi
}

function testUrl() {
  url=$@
  if $url -ks -f -o /dev/null
  then
    return 0
  else
    return 1
  fi;
}

function waitForService() {
  url=$@
  echo -n "Wait for: $url ... "
  n=0
  until testUrl $url
  do
    n=$((n + 1))
    if [[ $n == 10 ]]
    then
      echo " Give up"
      exit 1
    else
      sleep 3
      echo -n ", retry #$n "
    fi
  done
  echo "DONE, continues..."
}

function createComposite() {
  local composite=$1

  local LOCATION
  LOCATION=$(curl -s -D - -o /dev/null \
    -X POST "http://$HOST:$PORT/api/v1/aggregate/course" \
    -H "Content-Type: application/json" \
    --data "$composite" \
    | grep -i '^Location:' | awk '{print $2}' | tr -d '\r')

  # extract UUID (last path segment)
  local COURSE_ID
  COURSE_ID=$(basename "$LOCATION")

  echo "$COURSE_ID"
}

function setupTestdata() {
  local body='{"course": { "name": "course-bash-script" },
         "recommendations": [
               { "author": "author 1", "rate": 1, "content": "content 1" }
           ],
           "reviews": [
               { "author": "author 1", "subject": "subject 1", "content": "content 1" }
           ]
       }'
  local location=$(createComposite "$body")
  echo "$location"
}

set -e

echo "Start Tests:" $(date +"%Y/%m/%d %H:%M:%S")

echo "HOST=${HOST}"
echo "PORT=${PORT}"

if [[ $@ == "start" ]]
then
  echo "Restarting the test environment..."
  echo "$ docker compose down --remove-orphans"
  docker compose down --remove-orphans
  echo "$ docker compose up -d"
  docker compose up -d
fi
waitForService curl -X DELETE http://${HOST}:${PORT}/api/v1/aggregate/course/1fe92fa4-95bc-411a-8f2c-5d502b5f65f8

aggregateId=$(setupTestdata)

response=$(assertHttpCode 200 "http://${HOST}:${PORT}/api/v1/aggregate/course/${aggregateId}")
assertEqual $aggregateId $(echo $response | jq -r .course.courseId)
assertEqual 1 $(echo $response | jq ".recommendations | length")
assertEqual 3 $(echo $response | jq ".reviews | length")