server:
  port: 8888

spring.cloud.config.server.native.search-locations: file:${PWD}/config-repo

management.endpoint.health.show-details: "ALWAYS"
management.endpoint.web.exposure.include: "*"

---
spring.config.activate.on-profile: docker
spring.cloud.config.server.native.search-locations: file:/config-repo