server.port: 7002
spring:
  application.name: course-service
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      username: ${MONGODB_USERNAME:username}
      password: ${MONGODB_PASSWORD:password}
      database: course
      port: ${MONGODB_PORT:27017}
      authentication-database: admin
      auto-index-creation: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    username: ${RABBITMQ_USER:user}
    password: ${RABBITMQ_PWD:password}
    port: ${RABBITMQ_PORT:5672}
  cloud:
    function.definition: courseCreate;courseUpdate;courseDelete
    stream:
      default:
        group: ${spring.application.name}
        consumer:
          max-attempts: 3
          back-off-initial-interval: 1000
          back-off-max-interval: 10000
          back-off-multiplier: 2.0
      bindings:
        courseCreate-in-0.destination: course.create
        courseUpdate-in-0.destination: course.update
        courseDelete-in-0.destination: course.delete