server.port: 7002
logging:
  level:
    org:
      springframework:
        amqp: off
    com.netflix:
      eureka: off
      discovery: off
spring:
  application:
    name: course-service
  data:
    mongodb:
      host: "127.0.0.1"
      port: 27017
  rabbitmq:
    username: user
    password: password
    port: 5672
  cloud:
    stream:
      bindings:
        course-in-0:
          destination: course
          group: course-service
eureka:
  instance:
    appname: ${spring.application.name}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    healthcheck:
      enabled: true
    initial-instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 5

#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#          "*"
---
spring.config.activate.on-profile: docker
server.port: 8080
spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
  rabbitmq:
    host: rabbitmq

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/