spring.config.import: "configserver:"

spring:
  application.name: auth-server
  cloud.config:
    failFast: false
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 3
    uri: http://localhost:8888
    username: ${CONFIG_SERVER_USR}
    password: ${CONFIG_SERVER_PWD}
logging:
  level:
    root: trace
---
spring.config.activate.on-profile: docker
spring.cloud.config.uri: http://config-server:8888