server.port: 7004
spring:
  application:
    name: review-service
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "postgres"
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  cloud:
    function:
      definition: reviewCreate;reviewUpdate;reviewDelete
    stream:
      default:
        group: ${spring.application.name}
        consumer:
          max-attempts: 3
          back-off-initial-interval: 1000
          back-off-max-interval: 10000
          back-off-multiplier: 2.0
      bindings:
        reviewCreate-in-0:
          destination: review.create
        reviewUpdate-in-0:
          destination: review.update
        reviewDelete-in-0:
          destination: review.delete
eureka:
  instance:
    appname: ${spring.application.name}
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
  client:
    fetch-registry: false
    initialInstanceInfoReplicationIntervalSeconds: 10
    registryFetchIntervalSeconds: 5

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: "jdbc:postgresql://postgresql:5432/postgres"
server.port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/