server.port: 7004
spring:
  application.name: review-service
  config.import: "optional:configserver:"
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "postgres"
  rabbitmq:
    username: user
    password: password
    port: 5672
  cloud:
    function:
      definition: reviewCreate;reviewUpdate;reviewDelete
    stream:
      default:
        group: ${spring.application.name}
        consumer:
          max-attempts: 3
          back-off-initial-interval: 1000
          back-off-max-interval: 10000
          back-off-multiplier: 2.0
      bindings:
        reviewCreate-in-0:
          destination: review.create
        reviewUpdate-in-0:
          destination: review.update
        reviewDelete-in-0:
          destination: review.delete

eureka.client.fetch-registry: false

---
spring.config.activate.on-profile: dev
spring.cloud.config:
  uri: http://config:8080
  fail-fast: true
  retry:
    max-attempts: 10
    initial-interval: 1100
    max-interval: 1500
    multiplier: 1.2
