apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway.fullname" . }}-config
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "config/*").AsConfig | indent 2 }}
