server.port: 7005
spring:
  application.name: course-composite-service
  cloud:
    config.enabled: false
    stream.bindings:
      courseCreate-out-0.destination: course.create
      courseUpdate-out-0.destination: course.update
      courseDelete-out-0.destination: course.delete
      reviewCreate-out-0.destination: review.create
      reviewUpdate-out-0.destination: review.update
      reviewDelete-out-0.destination: review.delete
      recommendationCreate-out-0.destination: recommendation.create
      recommendationUpdate-out-0.destination: recommendation.update
      recommendationDelete-out-0.destination: recommendation.delete
  rabbitmq:
    username: user
    password: password
    port: 5672
springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
eureka:
  instance:
    appname: ${spring.application.name}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    healthcheck.enabled: true
    initial-instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    service-url.defaultZone: http://username:password@localhost:8761/eureka/
logging:
  level:
    com.netflix.eureka: info
    com.netflix.discovery: info