server.port: 7005
spring:
  application:
    name: course-composite-service
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  cloud:
    stream:
      bindings:
        course-out-0:
          destination: course
        review-out-0:
          destination: review
        recommendation-out-0:
          destination: recommendation
logging.level.org: debug
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5

management:
  endpoint:
    health:
      show-details: ALWAYS

springdoc:
  swagger-ui.path: /openapi/swagger-ui/index.html
  api-docs.path: /openapi/v3/api-docs

---
spring.config.activate.on-profile: docker
server.port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/