server.port: 7005
spring:
  application.name: course-composite-service
  cloud:
    stream.bindings:
      courseCreate-out-0.destination: course.create
      courseUpdate-out-0.destination: course.update
      courseDelete-out-0.destination: course.delete
      reviewCreate-out-0.destination: review.create
      reviewUpdate-out-0.destination: review.update
      reviewDelete-out-0.destination: review.delete
      recommendationCreate-out-0.destination: recommendation.create
      recommendationUpdate-out-0.destination: recommendation.update
      recommendationDelete-out-0.destination: recommendation.delete
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    username: ${RABBITMQ_USER:user}
    password: ${RABBITMQ_PWD:password}
    port: ${RABBITMQ_PORT:5762}
springdoc:
  swagger-ui:
    path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs